"""Render Codex instructions, native permissions, MCP config, and hooks."""

import json
from pathlib import Path
import shlex
import tomllib
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str((HERE / "shared").resolve()))
sys.path.insert(0, str((HERE.parent / "hooks/shared").resolve()))

from permissions import load_policy
from rendering import as_json, hook_group, rule_text


def codex_config(workspace: Path, home: Path, policy: dict, mcp: dict) -> str:
    # JSON string escaping is valid for the basic TOML strings used here.
    quote = json.dumps
    parts = ["# Generated by scripts/render-harnesses.py.",
             f"developer_instructions = {quote(rule_text(workspace, home))}",
             "", "[sandbox_workspace_write]",
             f"writable_roots = {quote(policy['directories'])}", ""]
    for name, spec in mcp.get("mcpServers", {}).items():
        parts.append(f"[mcp_servers.{quote(name)}]")
        for key in ("command", "url", "args"):
            if key in spec:
                parts.append(f"{key} = {quote(spec[key])}")
        if spec.get("env"):
            parts.append(f"[mcp_servers.{quote(name)}.env]")
            parts.extend(f"{quote(key)} = {quote(str(value))}" for key, value in spec["env"].items())
        parts.append("")
    result = "\n".join(parts)
    tomllib.loads(result)
    return result



def render(workspace: Path, home: Path, mcp: dict | None = None) -> dict[str, str]:
    if mcp is None:
        config = workspace / ".codex/config.toml"
        if config.exists():
            mcp = {"mcpServers": tomllib.loads(config.read_text()).get("mcp_servers", {})}
        else:
            mcp = json.loads((workspace / ".mcp.json").read_text())
    command = f"python3 {shlex.quote(str(workspace / '.codex/hooks/adapter.py'))}"
    hooks = {"hooks": {
        "PreToolUse": [hook_group(command, "^Bash$")],
        "PermissionRequest": [hook_group(command, "^(Bash|mcp__.*)$")],
    }}
    return {
        ".codex/config.toml": codex_config(workspace, home, load_policy(workspace, home), mcp),
        ".codex/hooks.json": as_json(hooks),
    }
