#!/usr/bin/env python3
"""Render machine-local harness configuration from shared workspace sources."""

import argparse
import json
from pathlib import Path
import re
import shlex
import sys
import tomllib

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "hooks"))

from permissions import expand, load_policy


def hook_group(command: str, matcher: str) -> dict:
    return {"matcher": matcher, "hooks": [{"type": "command", "command": command, "timeout": 5}]}


def claude_config(workspace: Path, home: Path, policy: dict) -> dict:
    config = expand(json.loads((workspace / ".claude/settings.template.json").read_text()), workspace, home)
    allow = [f"Bash({pattern})" for pattern in policy["shell"]]
    names = {"read": "Read", "write": "Write", "edit": "Edit", "multiedit": "MultiEdit", "notebookedit": "NotebookEdit"}
    for tool, patterns in policy["files"].items():
        allow.extend(f"{names[tool]}({pattern})" for pattern in patterns)
    allow.extend(f"WebFetch(domain:{host})" for host in policy["webDomains"])
    allow.extend(f"mcp__{name}__*" for name in policy["mcpServers"])
    allow.extend(f"Skill({name})" for name in policy["skills"])
    allow.extend(policy["tools"])
    config["permissions"] = {"allow": allow, "additionalDirectories": policy["directories"]}
    command = f"python3 {shlex.quote(str(workspace / 'hooks/dispatch.py'))} claude"
    config["hooks"] = {"PreToolUse": [hook_group(command, "Bash|Shell|WebFetch")]}
    return config


def rule_text(workspace: Path, home: Path) -> str:
    bodies = []
    paths = sorted((workspace / "rules").glob("*.md"), key=lambda p: (p.name != "workflow-server.md", p.name))
    for path in paths:
        text = path.read_text()
        match = re.match(r"\A---\n(.*?)\n---\n(.*)", text, re.S)
        if match and re.search(r"(?m)^alwaysApply:\s*true\s*$", match[1]):
            bodies.append(expand(match[2].strip(), workspace, home))
    return "\n\n".join(bodies)


def codex_config(workspace: Path, home: Path, policy: dict, mcp: dict) -> str:
    # JSON string escaping is valid for the basic TOML strings used here.
    quote = json.dumps
    parts = ["# Generated by scripts/render-harnesses.py.",
             f"developer_instructions = {quote(rule_text(workspace, home))}",
             "", "[sandbox_workspace_write]",
             f"writable_roots = {quote(policy['directories'])}", ""]
    for name, spec in mcp.get("mcpServers", {}).items():
        parts.append(f"[mcp_servers.{quote(name)}]")
        for key in ("command", "url", "args"):
            if key in spec:
                parts.append(f"{key} = {quote(spec[key])}")
        if spec.get("env"):
            parts.append(f"[mcp_servers.{quote(name)}.env]")
            parts.extend(f"{quote(key)} = {quote(str(value))}" for key, value in spec["env"].items())
        parts.append("")
    result = "\n".join(parts)
    tomllib.loads(result)
    return result


def render(workspace: Path, home: Path, mcp: dict) -> dict[str, str]:
    policy = load_policy(workspace, home)
    command = f"python3 {shlex.quote(str(workspace / 'hooks/dispatch.py'))}"
    codex_hooks = {"hooks": {
        "PreToolUse": [hook_group(command + " codex", "^Bash$")],
        "PermissionRequest": [hook_group(command + " codex", "^(Bash|mcp__.*)$")],
    }}
    as_json = lambda value: json.dumps(value, indent=2) + "\n"
    return {
        ".claude/settings.json": as_json(claude_config(workspace, home, policy)),
        ".codex/config.toml": codex_config(workspace, home, policy, mcp),
        ".codex/hooks.json": as_json(codex_hooks),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=ROOT)
    parser.add_argument("--home", type=Path, default=Path.home())
    parser.add_argument("--mcp-stdin", action="store_true", help="Read resolved MCP config from stdin")
    parser.add_argument("--check", action="store_true", help="Report outdated generated files without writing")
    args = parser.parse_args()
    workspace = args.workspace.resolve()
    if args.mcp_stdin:
        mcp = json.load(sys.stdin)
    elif (workspace / ".codex/config.toml").exists():
        existing = tomllib.loads((workspace / ".codex/config.toml").read_text())
        mcp = {"mcpServers": existing.get("mcp_servers", {})}
    else:
        mcp = json.loads((workspace / ".mcp.json").read_text())
    stale = []
    for relative, content in render(workspace, args.home, mcp).items():
        path = workspace / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"Rendered {path}")
    if stale:
        parser.exit(1, "Outdated harness config: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
